CREATE TABLE  users(
	id UUID  NOT NULL PRIMARY KEY,
	name VARCHAR(500) NOT NULL,
	username VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);

CREATE TABLE repos(
	id UUID  NOT NULL PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	user_id UUID REFERENCES users(id),
	issue_count BIGINT NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);


CREATE TABLE issues(
	id BIGSERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(500) NOT NULL,
	user_id UUID REFERENCES users(id),
	body VARCHAR(3000) NOT NULL,
	repo_id UUID REFERENCES repos(id),
	issue_number BIGINT NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);

CREATE TABLE comments(
	id BIGSERIAL NOT NULL PRIMARY KEY,
	user_id UUID REFERENCES users(id),
	body VARCHAR(3000) NOT NULL,
	issue_id BIGINT REFERENCES issues(id),
	repo_id UUID REFERENCES repos(id),
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);